apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: poc-nginx
  name: poc-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poc-nginx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: poc-nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "250m"