apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: poc-nignx
  name: poc-nignx
spec:
  containers:
  - image: nignx
    name: poc-nignx
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
