apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: poc-nginx
  name: poc-nginx
spec:
  containers:
  - image: nginx
    name: poc-nginx
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
