apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: poc-nignx
  name: poc-nignx
spec:
  ports:
  - name: 8080-80
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: poc-nignx
  type: ClusterIP
status:
  loadBalancer: {}
